name: Maven Build & Docker Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Docker Image
      run: docker build -t hostelapp:latest .

    - name: Stop Old Container if Running
      run: |
        if [ "$(docker ps -q -f name=hostelapp)" ]; then
          docker stop hostelapp
          docker rm hostelapp
        fi

    - name: Run New Container
      run: |
        docker run -d \
          --name hostelapp \
          -p 8888:8888 \
          hostelapp:latest
